services:
  todo:
    build:
      context: ./todo_app
    ports:
      - "8000:80"
    volumes:
      - todo_data:/app/data

  shorturl:
    build:
      context: ./shorturl_app
    ports:
      - "8001:80"
    volumes:
      - shorturl_data:/app/data

volumes:
  todo_data:
  shorturl_data: